# Generated by Django 4.1.6 on 2023-03-26 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_integration_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirement', models.PositiveIntegerField(default=0)),
                ('badge_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_watched', models.PositiveIntegerField(default=0)),
                ('animated_movies_watched', models.PositiveIntegerField(default=0)),
                ('documentaries_watched', models.PositiveIntegerField(default=0)),
                ('action_movies_watched', models.PositiveIntegerField(default=0)),
                ('comedy_movies_watched', models.PositiveIntegerField(default=0)),
                ('romance_movies_watched', models.PositiveIntegerField(default=0)),
                ('badges', models.ManyToManyField(to='home.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
