# Generated by Django 4.1.6 on 2023-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='genres',
            field=models.ManyToManyField(to='home.genre'),
        ),
    ]
