# Generated by Django 4.1.6 on 2023-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_animated_movies_watched_userprofile_adventure_movies_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='earned_badges', related_query_name='badge', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='requirement',
            field=models.IntegerField(),
        ),
    ]
