# Generated by Django 4.1.6 on 2023-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_badge_genre_badge_users_alter_badge_badge_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
