# Generated by Django 4.1.6 on 2023-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default=1, upload_to='badges/'),
            preserve_default=False,
        ),
    ]
